version: '3'
services:
  map-app:
    container_name: map-app
    build:
      context: .
      dockerfile: ./deployment/backend/Dockerfile
    ports:
      - 8500:8000
    volumes:
      - ./map:/home/map
    tty: true
    depends_on:
      - db
    networks:
      - map-network
  
  db:
    container_name: map-db
    image: postgres:14.5-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdb:/var/lib/postgresql/data
    networks:
      - map-network

  map-front:
    container_name: map-front
    build:
      context: .
      dockerfile: ./deployment/frontend/Dockerfile
    volumes:
      - ./frontend:/usr/src/map
    environment:
     - WATCHPACK_POLLING=true
    command: sh -c "cd map && npm run dev"
    ports:
      - 3000:3000
    networks:
      - map-network

volumes:
  pgdb:
    external: true

networks:
  map-network:
    external: true
