version: '3'
services:
  map-app:
    container_name: map-app
    build:
      context: .
      dockerfile: ./deployment/Dockerfile
    ports:
      - 8500:8000
    volumes:
      - ./map:/home/map
    tty: true