"""create country table

Revision ID: 19410f6f1273
Revises: 
Create Date: 2022-09-06 14:40:08.261465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19410f6f1273'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('jp_name', sa.String(), nullable=True),
    sa.Column('en_name', sa.String(), nullable=True),
    sa.Column('numeric_code', sa.Integer(), nullable=True),
    sa.Column('alpha2', sa.String(), nullable=True),
    sa.Column('area', sa.String(), nullable=True),
    sa.Column('administrative_division', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('countries')
    # ### end Alembic commands ###
