[tool.poetry]
name = "map"
version = "0.1.0"
description = ""
authors = ["mol2mol39@gmail.com"]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.81.0"
uvicorn = "^0.18.3"
strawberry-graphql = "^0.127.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
